---
title: "Compare sources and final series"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, warning=FALSE,message=FALSE}
library(magrittr)
library(stringr)
library(ggplot2)
library(plotly)
```

```{r configure, echo=FALSE}
raw_df <- read.csv("../raw_df.csv")
COUNTRY <- gsub(paste0(dirname(getwd()),"/"),"",getwd())
country_df <- subset(raw_df, country == COUNTRY)
final_series_list <- unique(subset(country_df, preferred_definition=="*")$series_code)
```


```{r fig.align="center",warning=FALSE,message=FALSE,echo=FALSE,fig.width = 14}
for (i in 1:length(final_series_list)){
    country_df <- subset(raw_df, country == COUNTRY)
    final_series_df <- subset(country_df, series_code == final_series_list[i])
    sources_used <- final_series_df$source_codes_used[i] %>% str_split(",")
    source_series_df <- subset(country_df, series_code == sources_used[[1]])
    cat(paste(final_series_list[i],"-",country_df[match(final_series_list[i],country_df$series_code),]$dimension))
    print(ggplot() + geom_point(data=source_series_df, aes(year,value,colour=legend)) + geom_line(data=final_series_df, aes(year,value)) + theme(legend.position="bottom"))
}
```
